### ISSUE TITLE
aarch64 not uploaded

### ISSUE THREAD

**Issue by philip-khor** [conda-forge/r-utf8-feedstock#7]
Issue:
Even though #6 has been merged there's no linux-aarch64 build uploaded to conda. In drone logs: 

> Distribution /drone/src/build_artifacts/linux-aarch64/r-utf8-1.1.4-r36hcdcec82_1002.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.

**Comment by dbast** [comment]
solved via https://github.com/conda-forge/r-utf8-feedstock/pull/9
